#!/usr/bin/env python2

import random

from d20_chargen import PHYSICAL_STATS
from d20_chargen import MENTAL_STATS
from d20_chargen import BASE_STATS
from d20_chargen import attack
from d20_chargen import choose_stat
from d20_chargen import generate_stats
from d20_chargen import raise_stats
from d20_chargen import handle_args
from d20_chargen import mod
from d20_chargen import report
from d20_chargen import save

if __name__ == "__main__":
    arguments = handle_args()
    level = arguments.level

    favored_stats = arguments.favor
    if not favored_stats:
        favored_stats = BASE_STATS
    unfavored_stats = list(set(BASE_STATS) - set(favored_stats))
    stats = generate_stats(favored_stats, unfavored_stats)

    improve_stats = arguments.improve
    if not improve_stats:
        improve_stats = favored_stats 
    raise_stats(stats, level, improve_stats)

    report(stats, level, arguments.base_attack, good_saves=arguments.good_saves,
          hitdie=arguments.hitdie)
